import { useState } from "react";
import { useIndustryData } from "@/hooks/useIndustryData";
import { mockKnowledgeDocuments } from "@/data/knowledgeBaseData";
import { motion } from "framer-motion";
import { Sparkles, Loader2, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

export default function DigestGenerator({ onInsert }: { onInsert?: (body: string) => void }) {
  const data = useIndustryData();
  const [generating, setGenerating] = useState(false);
  const [generatedBody, setGeneratedBody] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const generateDigest = () => {
    setGenerating(true);

    setTimeout(() => {
      const now = new Date();
      const weekStart = new Date(now);
      weekStart.setDate(now.getDate() - 7);
      const dateRange = `${weekStart.toLocaleDateString("en-US", { month: "short", day: "numeric" })} – ${now.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`;

      const { mostAsked, approvedCorrections, publishedContent } = data;
      const topQuestions = mostAsked.slice(0, 5);
      const recentDocs = mockKnowledgeDocuments
        .filter((d) => new Date(d.addedAt) > weekStart)
        .slice(0, 5);
      const recentCorrections = approvedCorrections.slice(0, 3);
      const recentContent = publishedContent
        .filter((c) => c.status === "published")
        .slice(0, 3);

      const body = `# Beacon Weekly — ${dateRange}

## 🔥 Trending This Week
${topQuestions.map((q, i) => `${i + 1}. ${q.question} (${q.timesAsked} asks)`).join("\n")}

## 📝 Knowledge Base Updates
${recentDocs.length > 0
  ? recentDocs.map((d) => `- **${d.title}** — ${d.category}`).join("\n")
  : "No new documents added this week."}

## ✅ Corrections Approved
${recentCorrections.map((c) => `- ${c.correctionApplied} *(approved by ${c.approvedBy})*`).join("\n")}

## 📰 Published Content
${recentContent.map((c) => `- **${c.title}** — ${c.views.toLocaleString()} views, ${c.shares} shares`).join("\n")}

## 📊 Quick Stats
- **Total Questions This Week:** ~${Math.floor(Math.random() * 50 + 150)}
- **Success Rate:** ${(92 + Math.random() * 4).toFixed(1)}%
- **New Documents Indexed:** ${recentDocs.length}

---
*Auto-generated by Beacon's Digest Engine · [Edit before sending]*`;

      setGeneratedBody(body);
      setGenerating(false);
      toast({ title: "Digest generated! ✨", description: "Review and edit before sending." });
    }, 2000);
  };

  const handleCopy = () => {
    if (!generatedBody) return;
    navigator.clipboard.writeText(generatedBody);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-xl border border-border bg-gradient-to-br from-card to-primary/5 p-5 shadow-card"
    >
      <div className="flex items-center gap-2 mb-1">
        <Sparkles className="h-5 w-5 text-primary" />
        <h3 className="font-mono text-sm font-semibold text-foreground">Weekly Digest Generator</h3>
      </div>
      <p className="text-xs text-muted-foreground mb-4">
        Auto-compile this week's questions, corrections, published content, and KB updates into a newsletter draft.
      </p>

      {!generatedBody && !generating && (
        <Button onClick={generateDigest} className="gap-1.5">
          <Sparkles className="h-3.5 w-3.5" /> Generate This Week's Digest
        </Button>
      )}

      {generating && (
        <div className="flex items-center gap-3 py-4">
          <Loader2 className="h-5 w-5 animate-spin text-primary" />
          <span className="text-sm text-muted-foreground">Compiling platform activity...</span>
        </div>
      )}

      {generatedBody && (
        <div className="space-y-3 mt-2">
          <div className="rounded-lg border border-border bg-card p-4 max-h-64 overflow-y-auto">
            <pre className="text-xs text-foreground whitespace-pre-wrap font-mono">{generatedBody}</pre>
          </div>
          <div className="flex gap-2">
            <Button size="sm" variant="outline" className="gap-1.5" onClick={handleCopy}>
              {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              {copied ? "Copied!" : "Copy"}
            </Button>
            {onInsert && (
              <Button
                size="sm"
                className="gap-1.5"
                onClick={() => {
                  onInsert(generatedBody);
                  toast({ title: "Inserted into composer", description: "Edit and send when ready." });
                }}
              >
                Use as Newsletter Draft
              </Button>
            )}
            <Button size="sm" variant="ghost" onClick={() => setGeneratedBody(null)}>
              Regenerate
            </Button>
          </div>
        </div>
      )}
    </motion.div>
  );
}
